# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_merge_20170713_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('SNo', models.IntegerField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='comments',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='Resultp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='Score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Cities', verbose_name='Which City you live in ?'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q2',
            field=models.IntegerField(choices=[(0, 'I am not particularly discouraged about the future.'), (1, 'I feel discouraged about the future'), (2, 'I feel I have nothing to look forward to.'), (3, 'I feel the future is hopeless and that things cannot improve.')]),
        ),
    ]
